# Generated by Django 3.2.6 on 2021-08-09 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flipkart_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ('price_difference', 'created')},
        ),
        migrations.AddField(
            model_name='link',
            name='lowest_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='link',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
